# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u02Ua-Y4STX1uIJA7tMrZ2teZazwdgYa
"""

Professor: Matheus Batista

Entrega Final da Fase 1
Implementar API REST funcional utilizando FastAPI ou Flask
Preparar a API para ser integrada com um modelo de análise de sentimentos
Deixar configurado:
Um método GET
Um método POST

Alunos: Rafael Barbosa e Ildefonso Melo
""""
from fastapi import FastAPI
from pydantic import BaseModel

# Criando a aplicação FastAPI
app = FastAPI(
    title="API de Análise de Sentimentos",
    description="API REST desenvolvida para a Fase 1 da disciplina, contendo um método GET e um método POST.",
    version="1.0.0"
)

# Método POST
class TextoEntrada(BaseModel):
    texto: str

# Método GET
@app.get("/")
def home():
    return {
        "mensagem": "API de análise de sentimentos funcionando com sucesso"
    }

# Método POST para receber um texto e retornar
@app.post("/sentimento")
def analisar_sentimento(dados: TextoEntrada):
    texto = dados.texto.lower()

    # Classificação do sentimento
    if "feliz" in texto or "ótimo" in texto or "bom" in texto or "excelente" in texto:
        sentimento = "positivo"
    elif "triste" in texto or "ruim" in texto or "péssimo" in texto or "horrível" in texto:
        sentimento = "negativo"
    else:
        sentimento = "neutro"

    return {
        "texto_recebido": dados.texto,
        "sentimento": sentimento,
        "observacao": "Esta API está preparada para futura integração com um modelo de IA para análise de sentimentos."
    }